spring:
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
    password: ${POSTGRES_DB_PASSWORD}
    username: ${POSTGRES_DB_USERNAME}
    driver-class-name: org.postgresql.Driver
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
