spring:
  application:
    name: user-service
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
    password: ${POSTGRES_DB_PASSWORD}
    username: ${POSTGRES_DB_USERNAME}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

