spring:
  application:
    name: user-service

server:
  port: 8081

userservice:
  rabbitmq:
    queue: userservice.queue
    exchange: user.internal.exchange
    routingKey: user.internal.notification.routing-key