#Workflow name
name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  runner-job:
    runs-on: ubuntu-latest

  services:
    postgres:
      image: postgres
    env:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: userservice
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        # Maps tcp port 5432 on service container to the host
        - 5432:5432


  build-and-test:
    name: Build and test
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build
        run: ./gradlew build
        env:
          POSTGRES_DB_HOST=localhost
          POSTGRES_DB_PORT=5432
          POSTGRES_DB_NAME=userservice
          POSTGRES_DB_USERNAME=postgres
          POSTGRES_DB_PASSWORD=postgres

      - name: Run Tests
        run: ./gradlew test
        env:
          POSTGRES_DB_HOST=localhost
          POSTGRES_DB_PORT=5432
          POSTGRES_DB_NAME=userservice
          POSTGRES_DB_USERNAME=postgres
          POSTGRES_DB_PASSWORD=postgres